### ISSUE TITLE
Bug causing hindrance in quill Preview 

### ISSUE THREAD

**Issue by ynisha11** [adamarla/qQuill#12]
Commands causing bug :-
1. \end{align}
2. & 

Whenever there is a syntax error in the question.xml file for the above commans, then:-
1. quill preview doesn't launch
2. Instead of displaying the syntax error in the box during preivew, the stack of error messages shows up in the terminal window.
![quillbug](https://cloud.githubusercontent.com/assets/10741297/8453732/23e562b4-2015-11e5-9014-9ca31e2142ec.png)
![quillbug2](https://cloud.githubusercontent.com/assets/10741297/8453764/798b74ec-2015-11e5-990e-a7966a2fb3aa.png)

**Comment by adamarla** [comment]
Fixed in Quill 1.1
