### ISSUE TITLE
Auto set cronjobs to push changes to server 

### ISSUE THREAD

**Issue by abhinavc** [adamarla/qQuill#15]
The author should not have to issue any git commands from the command-line. 
In particular, git push origin master and git pull-request. 

Hence, if a cronjob can be set by quill, then it should call the following script 
25 min and 55 min past the hour. 

vault/bin/push_to_server 

The script will need to be adapted for the user's local vault/ path.

**Comment by adamarla** [comment]
On Quill - Clerk: File > Sync
`git fetch upstream`, followed by `git merge upstream/master` followed by `git push origin master` 
On Quill - Edit: File > Save + Commit
`git add / rm` followed by `git commit`

**Comment by adamarla** [comment]
Quill - Clerk: File > Sync Files (keyboard shortcut Ctrl+Y) now does the following
`git fetch upstream`
`git merge upstream/master`
`git push origin master`
`hub pull-request gutenberg:master`

If it is working fine will make it part of normal quill launch
