### ISSUE TITLE
Calling quill -t from an empty folder causes a crash 

### ISSUE THREAD

**Issue by abhinavc** [adamarla/qQuill#8]
If a question folder does not have a question.xml, then calling quill -t gives a 
java.lang.ArrayIndexOutOfBoundsException: 1

If question.xml only signals one's presence somewhere inside vault/, then 
that basis should change. Ideally, one should be able to call quill -t 
from anywhere between vault/ -> vault/eid/qid/. But at a bare minimum from vault/eid/

**Comment by adamarla** [comment]
adamarla@brooklyn:~/work/gutenberg/vault/2/enh/zdwp5$ quill -t
adamarla@brooklyn:~/work/gutenberg/vault/2/enh/zdwp5$ ls -lrt question.xml
ls: cannot access question.xml: No such file or directory
adamarla@brooklyn:~/work/gutenberg/vault/2/enh/zdwp5$

Doesn't cause a crash for me. May be you don't have the latest Qquill.jar.

Anyway, I'll enhance it to run from at least one level above a question directory.

**Comment by adamarla** [comment]
Fixed.
